### ISSUE TITLE
Test media sets to be used in testing

### ISSUE THREAD

**Issue by viliman** [rameplayerorg/rameplayer-testing#8]
One short 5clips or so 10-15min 720p, One longer set n. 2h various sizes of clips 720p. Both in English language audio track. 

Then if possible language replicas for short and long in different languages 4 pieces.

**Comment by TaruVare** [comment]
Short and long media lists done (although short is less than 10 min, 5 pieces). Please check and comment if edit needed. Also different languages linked from short list. Is the format ok, or should those be tabled as English versions are tabled (with title names etc.)?

**Comment by viliman** [comment]
This is excellent - thanks a lot!
